/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Nikhil;

import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.CallableStatement;

/**
 *
 * @author ELCOT
 */
public class clgwisecost extends javax.swing.JFrame {

    /**
     * Creates new form clgwisecost
     */
    String l;
    public clgwisecost(){}
    public clgwisecost(String s) {
        initComponents();
        l=s;
        name1.setText(""); dep1.setText(""); cost1.setText("");
        name2.setText(""); dep2.setText(""); cost2.setText("");
        name3.setText(""); dep3.setText(""); cost3.setText("");
        name4.setText(""); dep4.setText(""); cost4.setText("");
        name5.setText(""); dep5.setText(""); cost5.setText("");
        Connection conn=null;
        try
       {String driverName="oracle.jdbc.driver.OracleDriver";
           Class.forName(driverName);
           String serverName="localhost";
           String serverPort="1521";
           String sid="Prassy";
           String url="jdbc:oracle:thin:@localhost:1521/Prassy";
           String username="nikhilproject";
           String password="nikki";
           conn=DriverManager.getConnection(url,username,password);
           System.out.println("Connected");
           Statement st=conn.createStatement();
           ResultSet rs=st.executeQuery("select symp_name,dep_id,cost from symposium where clg_code="+l+"");
           String name[]= new String[5];
           String dep[]=new String[5];
           String cost[]=new String[5]; 
           int i=0;
           while(rs.next() && i<5)
           {
               name[i]=rs.getString(1);
               dep[i]=rs.getString(2);
               cost[i]=rs.getString(3);
               i++;
           }
           name1.setText(name[0]);
           name2.setText(name[1]);
           name3.setText(name[2]);
           name4.setText(name[3]);
           name5.setText(name[4]);
           dep1.setText(dep[0]);
           dep2.setText(dep[1]);
           dep3.setText(dep[2]);
           dep4.setText(dep[3]);
           dep5.setText(dep[4]);
           cost1.setText(cost[0]);
           cost2.setText(cost[1]);
           cost3.setText(cost[2]);
           cost4.setText(cost[3]);
           cost5.setText(cost[4]);
           CallableStatement cs; 
           String str="select computeSympcost(?) from dual";
                        cs=conn.prepareCall(str);
                        cs.setString(1,l);
                        ResultSet rs1=cs.executeQuery();
                        try{
                            while(rs1.next()){
                                String g=rs1.getString(1);
                                totcost.setText(g);
                            }
                        }
                        catch(SQLException ex){
                            System.out.println(ex);
                        }
       }
       
       catch(ClassNotFoundException | SQLException e)
       {
           System.out.println(e);
       }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        name1 = new javax.swing.JLabel();
        name2 = new javax.swing.JLabel();
        name3 = new javax.swing.JLabel();
        name4 = new javax.swing.JLabel();
        name5 = new javax.swing.JLabel();
        dep1 = new javax.swing.JLabel();
        dep2 = new javax.swing.JLabel();
        dep3 = new javax.swing.JLabel();
        dep4 = new javax.swing.JLabel();
        dep5 = new javax.swing.JLabel();
        cost1 = new javax.swing.JLabel();
        cost2 = new javax.swing.JLabel();
        cost3 = new javax.swing.JLabel();
        cost4 = new javax.swing.JLabel();
        cost5 = new javax.swing.JLabel();
        totcost = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("COLLEGE WISE SYMPOSIUM LIST");

        jLabel2.setText("NAME");

        jLabel3.setText("DEPARTMENT");

        jLabel4.setText("COST");

        name1.setText("jLabel5");

        name2.setText("jLabel6");

        name3.setText("jLabel7");

        name4.setText("jLabel8");

        name5.setText("jLabel9");

        dep1.setText("jLabel5");

        dep2.setText("jLabel6");

        dep3.setText("jLabel7");

        dep4.setText("jLabel8");

        dep5.setText("jLabel9");

        cost1.setText("jLabel5");

        cost2.setText("jLabel6");

        cost3.setText("jLabel7");

        cost4.setText("jLabel8");

        cost5.setText("jLabel9");

        totcost.setText("jLabel5");

        jLabel5.setText("TOTAL COST :");

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(name1)
                    .addComponent(name5)
                    .addComponent(name4)
                    .addComponent(name3)
                    .addComponent(name2)
                    .addComponent(jButton1))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(87, 87, 87))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                                .addComponent(totcost))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dep5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cost5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dep4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cost4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dep3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cost3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dep2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cost2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dep1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cost1)))
                        .addGap(79, 79, 79))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name1)
                    .addComponent(dep1)
                    .addComponent(cost1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name2)
                    .addComponent(dep2)
                    .addComponent(cost2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name3)
                    .addComponent(dep3)
                    .addComponent(cost3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name4)
                    .addComponent(dep4)
                    .addComponent(cost4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name5)
                    .addComponent(dep5)
                    .addComponent(cost5))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totcost)
                    .addComponent(jLabel5)
                    .addComponent(jButton1))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(clgwisecost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(clgwisecost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(clgwisecost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(clgwisecost.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new clgwisecost().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cost1;
    private javax.swing.JLabel cost2;
    private javax.swing.JLabel cost3;
    private javax.swing.JLabel cost4;
    private javax.swing.JLabel cost5;
    private javax.swing.JLabel dep1;
    private javax.swing.JLabel dep2;
    private javax.swing.JLabel dep3;
    private javax.swing.JLabel dep4;
    private javax.swing.JLabel dep5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel name1;
    private javax.swing.JLabel name2;
    private javax.swing.JLabel name3;
    private javax.swing.JLabel name4;
    private javax.swing.JLabel name5;
    private javax.swing.JLabel totcost;
    // End of variables declaration//GEN-END:variables
}
